<?php

$liste = 
'{"DE__734P":"Alte Weser, Leuchtturm",
"DE__732A":"Altengamme",
"DE__622P":"Amrum Odde",
"DE__631P":"Amrum, Hafen (Wittdün)",
"DE__773P":"Arngast, Leuchtturm ",
"DE__784P":"Baltrum, Westende ",
"DE__816B":"Barßel, Soeste",
"DE__683P":"Belum, Oste ",
"DE__782P":"Bensersiel",
"DE__715P":"Blankenese, Unterfeuer",
"DE__666P":"Blauort ",
"DE__750D":"Borgfeld, Wümme ",
"DE__101P":"Borkum, Fischerbalje",
"DE__798P":"Borkum, Südstrand ",
"DE__743P":"Brake ",
"DE__693P":"Breitenberg, Stör ",
"DE__502P":"Bremen, Oslebshausen",
"DE__752P":"Bremen, Weserwehr ",
"DE__751P":"Bremen, Wilhelm-Kaisen-Brücke ",
"DE__103P":"Bremerhaven, Alter Leuchtturm ",
"DE__740P":"Bremerhaven, Doppelschleuse ",
"DE__687P":"Bremervörde, Oste ",
"DE__688P":"Brokdorf",
"DE__504P":"Brunsbüttel ",
"DE__729P":"Bunthaus",
"DE__505P":"Büsum ",
"DE__745A":"Buttelerhörne, Hunte",
"DE__718P":"Buxtehude, Este ",
"DE__717P":"Cranz, Este - Sperrwerk, Außenp",
"DE__506P":"Cuxhaven, Steubenhöft ",
"DE__635P":"Dagebüll",
"DE__669P":"Deichsiel ",
"DE__810B":"Detern, Jümme ",
"DE__783P":"Dornumer - Accumersiel",
"DE__727P":"Dove - Elbe, Einfahrt ",
"DE__812P":"Dreyschloot, Leda ",
"DE__799G":"Dukegat ",
"DE__737P":"Dwarsgat, Unterfeuer",
"DE__664P":"Eidersperrwerk, Außenpegel",
"DE__702P":"Elmshorn, Krückau ",
"DE__744A":"Elsfleth Ohrt ",
"DE__744P":"Elsfleth",
"DE__507P":"Emden, Große Seeschleuse",
"DE__799P":"Emshörn ",
"DE__730C":"Fahrenholz, Ilmenau ",
"DE__749P":"Farge ",
"DE__738P":"Fedderwardersiel",
"DE__632P":"Föhr, Wyk ",
"DE__629B":"Föhrer Ley Nord ",
"DE__675P":"Friedrichskoog, Hafen ",
"DE__671D":"Friedrichskoog, Spitze",
"DE__662E":"Friedrichstadt, Eider ",
"DE__732D":"Geesthacht, Wehr UP ",
"DE__695P":"Glückstadt",
"DE__703P":"Grauerort ",
"DE__637P":"Gröde, Anleger",
"DE__508P" :"Hamburg, St. Pauli",
"DE__724P":"Harburg, Schleuse ",
"DE__778P":"Harlesiel ",
"DE__685P":"Hechthausen, Oste ",
"DE__509A":"Helgoland, Binnenhafen",
"DE__816P":"Herbrum, Hafendamm, Ems ",
"DE__711P":"Hetlingen ",
"DE__746P":"Hollersiel, Hunte ",
"DE__649B":"Holmer Siel ",
"DE__636F":"Hooge, Anleger",
"DE__765P":"Hooksiel",
"DE__764B":"Hooksielplate ",
"DE__624P":"Hörnum, Hafen ",
"DE__624A":"Hörnum, West",
"DE__745P":"Huntebrück, Hunte ",
"DE__510P":"Husum ",
"DE__730A":"Ilmenau - Sperrwerk, Außenpegel",
"DE__692P":"Itzehoe, Stör ",
"DE__794P":"Juist, Hafen",
"DE__620K":"Kampen, West",
"DE__691R":"Kasenort, Stör",
"DE__802P":"Knock ",
"DE__698P":"Kollmar (Kamperreihe) ",
"DE__697P":"Krautsand ",
"DE__700P":"Krückau - Sperrwerk, Außenpegel",
"DE__700R":"Krückau - Sperrwerk, Binnenpege",
"DE__632D":"Langeness Hilligenley ",
"DE__781P":"Langeoog",
"DE__808A":"Leda - Sperrwerk, Unterpegel",
"DE__808P":"Leer, Schleuse, Leda",
"DE__806P":"Leerort, Ems",
"DE__796C":"Leybucht, Leyhörn ",
"DE__658B":"Linnenplate ",
"DE__616P":"List West ",
"DE__617P":"List",
"DE__712P":"Lühort, Lühe",
"DE__667B":"Meldorf - Sperrwerk, Außenpegel",
"DE__760P":"Mellumplate, Leuchtturm ",
"DE__795B":"Memmert ",
"DE__675C":"Mittelplate ",
"DE__618P":"Munkmarsch",
"DE__785P":"Neßmersiel",
"DE__810A":"Neuburg, Jümme",
"DE__681A":"Neufeld, Hafen",
"DE__780P":"Neuharlingersiel",
"DE__678W":"Neuwerk ",
"DE__750C":"Niederblockland, Wümme",
"DE__790A":"Norddeich, Westerriede",
"DE__741A":"Nordenham, Unterfeuer ",
"DE__111P":"Norderney, Riffgat",
"DE__663E":"Nordfeld, Eider ",
"DE__649P":"Nordstrand, Strucklahnungshörn",
"DE__750G":"Ochtum - Sperrwerk, Oberpegel ",
"DE__748P":"Oldenburg - Drielake, Hunte ",
"DE__682P":"Osteriff",
"DE__681P":"Otterndorf",
"DE__730P":"Over",
"DE__814P":"Papenburg, Ems",
"DE__647A":"Pellworm, Anleger ",
"DE__642E":"Pellworm, Hoogerfähre ",
"DE__726A":"Peute ",
"DE__704P":"Pinnau - Sperrwerk, Außenpegel",
"DE__704R":"Pinnau - Sperrwerk, Binnenpegel",
"DE__803P":"Pogum, Ems",
"DE__811P":"Potshausen, Leda",
"DE__621R":"Rantum, West",
"DE__623A":"Rantumdamm",
"DE__741B":"Rechtenfleth",
"DE__747P":"Reithörne, Hunte",
"DE__814B":"Rhede, Ems",
"DE__750B":"Ritterhude, Hamme ",
"DE__737S":"Robbensüdsteert ",
"DE__642C":"Rummelloch, West",
"DE__677B":"Sahlenburg",
"DE__677P":"Scharhörn ",
"DE__677C":"Scharhörnriff, Bake A ",
"DE__761P":"Schillig",
"DE__638P":"Schlüttsiel ",
"DE__714P":"Schulau ",
"DE__720P":"Seemannshöft",
"DE__735A":"Spieka Neufeld",
"DE__779P":"Spiekeroog",
"DE__709P":"Stadersand, Schwinge",
"DE__690P":"Stör - Sperrwerk, Außenpegel",
"DE__690R":"Stör - Sperrwerk, Binnenpegel ",
"DE__637A":"Strand, Hamburger Hallig",
"DE__645P":"Süderoogsand",
"DE__653P":"Südfall, Fahrwasserkante",
"DE__634P":"Südwesthörn ",
"DE__805P":"Terborg, Meßstelle, Ems ",
"DE__661E":"Tönning, Eider",
"DE__673P":"Trischen, West",
"DE__655D":"Tümlauer Hafen",
"DE__706P":"Uetersen, Pinnau",
"DE__776P":"Vareler Schleuse",
"DE__750P":"Vegesack",
"DE__766P":"Voslapp ",
"DE__754P":"Wangerooge, Langes Riff, (Nord)",
"DE__756P":"Wangerooge, Ost ",
"DE__777P":"Wangerooge, West",
"DE__763P":"Wangertief, Horumersiel ",
"DE__750A":"Wasserhorst, Lesum",
"DE__813P":"Weener, Ems ",
"DE__620P":"Westerland",
"DE__810P":"Westringaburg, Leda ",
"DE__512P":"Wilhelmshaven, Alter Vorhafen ",
"DE__770P":"Wilhelmshaven, Neuer Vorhafen ",
"DE__769P":"Wilhelmshaven, ölpier ",
"DE__809P":"Wiltshausen, Leda ",
"DE__696P":"Wischhafen - Sperrwerk",
"DE__735B":"Wremertief",
"DE__676P":"Zehnerloch",
"DE__731P":"Zollenspieker"}';

$i=0;
$out = array();
foreach(json_decode($liste) AS $key=>$label) {
	$i++;
//	if ($i> 5) break;
	$url = 'http://www.bsh.de/cgi-bin/gezeiten/was_tab.pl?ort=' . $key .'&zone=Gesetzliche+Zeit+%B9&niveau=KN';
	$page = file($url);
	foreach($page AS $line) {
		if (preg_match("|^(.*?)&#160;&#160;&#160;(.*?)<br>|",$line,$m)) {
			$lat = substr($m[1],0,2) + substr($m[1],3,2)/60 + substr($m[1],6,2)/3600;
			$lng = substr($m[2],0,2) + substr($m[2],3,2)/60 + substr($m[2],6,2)/3600;
			$sql .= "INSERT INTO loc SET (label,id,gps) VALUES ('".$label."','".$key."','".$lat.','.$lng."');\n";
			$item = null;
			$item->label = $label;
			$item->gps = $lat.','.$lng;
			$item->id = $key;
			array_push($out,$item);
		}
	}
}
print_r(json_encode($out));

